### ISSUE TITLE
Automating updates to this repository?

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/testsuite#84]
Would there be interest in perhaps configuring a github action to automatically run `update-testsuite.sh`, perhaps weekly, and make PRs? It could also range from auto-merging changes to the repository to just make a PR and let a human manually approve and merge.

**Comment by sunfishcode** [comment]
Sounds good to me. Running the script isn't a major burden today, but if someone wanted to automate it, that would be nice.
